export const PERMISSIONS = {
  // Student permissions
  VIEW_LESSONS: "VIEW_LESSONS",
  SUBMIT_EXERCISE: "SUBMIT_EXERCISE",
  VIEW_PROGRESS: "VIEW_PROGRESS",
  USE_AI_CHAT: "USE_AI_CHAT",
  VIEW_LEADERBOARD: "VIEW_LEADERBOARD",
  MANAGE_SRS_CARDS: "MANAGE_SRS_CARDS",
  VIEW_STUDENT_DASHBOARD: "VIEW_STUDENT_DASHBOARD",

  // Instructor permissions
  CREATE_LESSON: "CREATE_LESSON",
  EDIT_LESSON: "EDIT_LESSON",
  DELETE_LESSON: "DELETE_LESSON",
  PUBLISH_LESSON: "PUBLISH_LESSON",
  VIEW_STUDENT_ANALYTICS: "VIEW_STUDENT_ANALYTICS",
  GENERATE_AI_MATERIAL: "GENERATE_AI_MATERIAL",
  MANAGE_OWN_COURSES: "MANAGE_OWN_COURSES",
  VIEW_INSTRUCTOR_DASHBOARD: "VIEW_INSTRUCTOR_DASHBOARD",

  // Admin permissions
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ALL_CONTENT: "MANAGE_ALL_CONTENT",
  VIEW_SYSTEM_HEALTH: "VIEW_SYSTEM_HEALTH",
  MANAGE_LANGUAGES: "MANAGE_LANGUAGES",
  VIEW_ADMIN_DASHBOARD: "VIEW_ADMIN_DASHBOARD",
  MANAGE_AUDIT_LOGS: "MANAGE_AUDIT_LOGS",
  BULK_OPERATIONS: "BULK_OPERATIONS",
};

export const ROLE_PERMISSIONS = {
  ADMIN: [
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ALL_CONTENT,
    PERMISSIONS.VIEW_SYSTEM_HEALTH,
    PERMISSIONS.MANAGE_LANGUAGES,
    PERMISSIONS.MANAGE_AUDIT_LOGS,
    PERMISSIONS.BULK_OPERATIONS,
    PERMISSIONS.VIEW_LESSONS,
    PERMISSIONS.VIEW_STUDENT_ANALYTICS,
    PERMISSIONS.CREATE_LESSON,
    PERMISSIONS.EDIT_LESSON,
    PERMISSIONS.DELETE_LESSON,
    PERMISSIONS.PUBLISH_LESSON,
  ],

  INSTRUCTOR: [
    PERMISSIONS.VIEW_INSTRUCTOR_DASHBOARD,
    PERMISSIONS.CREATE_LESSON,
    PERMISSIONS.EDIT_LESSON,
    PERMISSIONS.DELETE_LESSON,
    PERMISSIONS.PUBLISH_LESSON,
    PERMISSIONS.VIEW_STUDENT_ANALYTICS,
    PERMISSIONS.GENERATE_AI_MATERIAL,
    PERMISSIONS.MANAGE_OWN_COURSES,
    PERMISSIONS.VIEW_LESSONS,
    PERMISSIONS.USE_AI_CHAT,
  ],

  STUDENT: [
    PERMISSIONS.VIEW_STUDENT_DASHBOARD,
    PERMISSIONS.VIEW_LESSONS,
    PERMISSIONS.SUBMIT_EXERCISE,
    PERMISSIONS.VIEW_PROGRESS,
    PERMISSIONS.USE_AI_CHAT,
    PERMISSIONS.VIEW_LEADERBOARD,
    PERMISSIONS.MANAGE_SRS_CARDS,
  ],
};
